# GitHub vidi samo ove varijable, ali ne i stvarne podatke!
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate produkcijske postavke
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Sigurnost: Isključi prikaz SQL upita u produkcijskim logovima
spring.jpa.show-sql=false